name: Page
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
      - run: java ./src/main/java/com.mtab.adventofcode/year2022/challenge2022
